/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.objHabitacion;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import Datos.estructuras;

/**
 *
 * @author sebas
 */
public class frmHabitacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmHabitacion.class.getName());

    /**
     * Creates new form frmHabitacion
     */
    
    estructuras datos = new estructuras();
    
    public frmHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdentificacion = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblObserv = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        lblClase = new javax.swing.JLabel();
        lblEdificio = new javax.swing.JLabel();
        lblPiso = new javax.swing.JLabel();
        cmbxCategoria = new javax.swing.JComboBox<>();
        cmbxClase = new javax.swing.JComboBox<>();
        cmbxEdificio = new javax.swing.JComboBox<>();
        cmbxEstado = new javax.swing.JComboBox<>();
        txtIdentificacion = new javax.swing.JTextField();
        txtPiso = new javax.swing.JSpinner();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObserva = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Habitaciones");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        lblIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdentificacion.setText("Identificación:");

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setText("Edificio:");

        lblObserv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblObserv.setText("Observaciones:");

        lblCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria.setText("Categoría: ");

        lblUbicacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUbicacion.setForeground(new java.awt.Color(0, 102, 153));
        lblUbicacion.setText("Ubicación");

        lblClase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClase.setText("Clase: ");

        lblEdificio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEdificio.setText("Edificio:");

        lblPiso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPiso.setText("Piso:");

        cmbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estandar", "Premium", "Deluxe" }));
        cmbxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxCategoriaItemStateChanged(evt);
            }
        });
        cmbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxCategoriaActionPerformed(evt);
            }
        });

        cmbxClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sencilla", "Dobles", "Triples", "Cuádruples" }));
        cmbxClase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxClaseItemStateChanged(evt);
            }
        });
        cmbxClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxClaseActionPerformed(evt);
            }
        });

        cmbxEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arenal", "Miravalles", "Poas", "Platanar" }));
        cmbxEdificio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxEdificioItemStateChanged(evt);
            }
        });
        cmbxEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxEdificioActionPerformed(evt);
            }
        });

        cmbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmbxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxEstadoItemStateChanged(evt);
            }
        });
        cmbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxEstadoActionPerformed(evt);
            }
        });

        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });

        txtPiso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/document-save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/application-exit.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gtk-dnd.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/document-preview.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txtObserva.setColumns(20);
        txtObserva.setRows(5);
        jScrollPane1.setViewportView(txtObserva);

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblObserv)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblIdentificacion)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtIdentificacion))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblClase)
                                        .addGap(89, 89, 89)
                                        .addComponent(cmbxClase, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEdificio)
                                            .addComponent(lblUbicacion))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbxEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblCategoria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPiso)
                                            .addComponent(lblEstado))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(52, 52, 52)
                                .addComponent(btnBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(btnModificar)))
                        .addGap(54, 54, 54)
                        .addComponent(btnConsultar)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacion)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(cmbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClase)
                    .addComponent(cmbxClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(lblUbicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdificio)
                    .addComponent(cmbxEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPiso)
                    .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cmbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObserv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnConsultar)))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxCategoriaActionPerformed

    private void cmbxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxCategoriaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxCategoriaItemStateChanged

    private void cmbxClaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxClaseItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxClaseItemStateChanged

    private void cmbxClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxClaseActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void cmbxEdificioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxEdificioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxEdificioItemStateChanged

    private void cmbxEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxEdificioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxEdificioActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String regex = "^\\d+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtIdentificacion.getText());

        if (matcher.matches()){
            if (datos.buscarBorrar(Integer.parseInt(txtIdentificacion.getText() ))){
                JOptionPane.showMessageDialog(this, "Habitacion borrada!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtIdentificacion.setText("");
            } else{
                JOptionPane.showMessageDialog(this, "Id no encontrado...", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo indentificacion solo admite numeros", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtIdentificacion.setText("");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String regex = "^\\d+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtIdentificacion.getText());

        if ( matcher.matches() ){
            int id = Integer.parseInt(txtIdentificacion.getText()); 
            int nuevaCate; int nuevaClase; int nuevEdif; int nuevEstado; int nuevoPiso;
            String nuevDetalle; 
            objHabitacion modHab = datos.getHabitacion(id);
            
            if ( modHab != null ) {
                int respuesta = JOptionPane.showConfirmDialog(this, "Se encontró la habitación, desea modificarla con los valores actuales?", "Aviso", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION){
                    int idx = datos.getIndex(id);
                    nuevaCate = cmbxCategoria.getSelectedIndex();
                    nuevaClase = cmbxClase.getSelectedIndex();
                    nuevEdif = cmbxEdificio.getSelectedIndex();
                    nuevEstado = cmbxEstado.getSelectedIndex();
                    nuevDetalle = txtObserva.getText();
                    Object valor = txtPiso.getValue();
                    Number valSpin = (Number) valor;
                    nuevoPiso = valSpin.intValue();
                    
                    objHabitacion modiHab = new objHabitacion(id, nuevaCate, nuevaClase, nuevEdif, nuevoPiso, nuevEstado, nuevDetalle);
                    datos.modHab(idx, modiHab);
                    
                    txtIdentificacion.setText("");
                    txtObserva.setText("");
                    cmbxCategoria.setSelectedIndex(0);
                    cmbxClase.setSelectedIndex(0);
                    cmbxEdificio.setSelectedIndex(0);
                    cmbxEstado.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(this, "Se modificó la habitación!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El id digitado no existe", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtIdentificacion.setText("");
            }
        
        } else {
            JOptionPane.showMessageDialog(this, "El campo indentificacion solo admite numeros", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtIdentificacion.setText("");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int id; int categ; int clase; int edificio; int piso; int estado;
        String observacion;
        
        if (txtIdentificacion.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", 
                                       "Aviso Importante", JOptionPane.WARNING_MESSAGE);
  
        } else {
            String regex = "^\\d+$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(txtIdentificacion.getText());
            if (matcher.matches()){
                id = Integer.parseInt(txtIdentificacion.getText());
                categ = cmbxCategoria.getSelectedIndex();
                clase = cmbxClase.getSelectedIndex();
                edificio = cmbxEdificio.getSelectedIndex();

                Object valor = txtPiso.getValue();
                Number valSpin = (Number) valor;
                piso = valSpin.intValue();
                estado = cmbxEstado.getSelectedIndex();
                observacion = txtObserva.getText();

                objHabitacion habitacion = new objHabitacion(id, categ, clase, edificio, piso, estado, observacion);
                habitacion.mostrarInfo();
                
                datos.agregarHab(habitacion);

                JOptionPane.showMessageDialog(this, "Informacion guardada!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            
                txtIdentificacion.setText("");
                txtObserva.setText("");
                cmbxCategoria.setSelectedIndex(0);
                cmbxClase.setSelectedIndex(0);
                cmbxEdificio.setSelectedIndex(0);
                cmbxEstado.setSelectedIndex(0);
            } else { 
                JOptionPane.showMessageDialog(this, "El campo indentificacion solo admite numeros", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtIdentificacion.setText("");
            }
        }
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxEstadoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxEstadoItemStateChanged

    private void cmbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxEstadoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String regex = "^\\d+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtIdentificacion.getText());
        
        if (matcher.matches()){
            int id = Integer.parseInt(txtIdentificacion.getText());
            objHabitacion hab = datos.getHabitacion( id );
            
            if (hab != null){
                JOptionPane.showMessageDialog(this, "Habitación encontrada!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtObserva.setText(hab.getDetalles());
                cmbxCategoria.setSelectedIndex(hab.getCategoria());
                cmbxClase.setSelectedIndex(hab.getClase());
                cmbxEdificio.setSelectedIndex(hab.getEdificio());
                cmbxEstado.setSelectedIndex(hab.getEstado());
            } else {
                JOptionPane.showMessageDialog(this, "El id digitado no existe", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtIdentificacion.setText("");
            }
            
        } else{
            JOptionPane.showMessageDialog(this, "El campo indentificacion solo admite numeros", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtIdentificacion.setText("");
        txtObserva.setText("");
        cmbxCategoria.setSelectedIndex(0);
        cmbxClase.setSelectedIndex(0);
        cmbxEdificio.setSelectedIndex(0);
        cmbxEstado.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "Datos limpiados!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmHabitacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbxCategoria;
    private javax.swing.JComboBox<String> cmbxClase;
    private javax.swing.JComboBox<String> cmbxEdificio;
    private javax.swing.JComboBox<String> cmbxEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblClase;
    private javax.swing.JLabel lblEdificio;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblObserv;
    private javax.swing.JLabel lblPiso;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextArea txtObserva;
    private javax.swing.JSpinner txtPiso;
    // End of variables declaration//GEN-END:variables
}
