/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import Datos.estructuras;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import Datos.objDetReserva;
import Datos.objEncReserva;

/**
 *
 * @author sebas
 */
public class frmReservas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmReservas.class.getName());

    /**
     * Creates new form frmReservas
     */
    estructuras datos = new estructuras();
    
    public frmReservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero = new javax.swing.JLabel();
        lblCedCli = new javax.swing.JLabel();
        lblNomCli = new javax.swing.JLabel();
        lblDetalles = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cmbxEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        txtCliente = new javax.swing.JTextField();
        txtCedCli = new javax.swing.JTextField();
        txtConsecutivo = new javax.swing.JTextField();
        lblHabitacion = new javax.swing.JLabel();
        lblCatHab = new javax.swing.JLabel();
        lblFechaIni = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblClaseHab = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        txtIdHab = new javax.swing.JTextField();
        txtCat = new javax.swing.JTextField();
        txtClaseHab = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        dtpInicio = new com.toedter.calendar.JDateChooser();
        dtpFin = new com.toedter.calendar.JDateChooser();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservaciones");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumero.setText("Consecutivo:");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 23, -1, -1));

        lblCedCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCedCli.setText("Cédula Cliente:");
        getContentPane().add(lblCedCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 23, -1, -1));

        lblNomCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomCli.setText("Nombre del cliente:");
        getContentPane().add(lblNomCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 23, -1, -1));

        lblDetalles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDetalles.setText("Observaciones:");
        getContentPane().add(lblDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 117, -1, -1));

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setText("Estado:");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 117, -1, -1));

        cmbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reservado", "En Ejecución", "Cancelada", "Finalizado" }));
        getContentPane().add(cmbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 152, -1, -1));

        txtDetalles.setColumns(20);
        txtDetalles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDetalles.setRows(5);
        jScrollPane1.setViewportView(txtDetalles);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 152, 339, 50));

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 58, 180, -1));

        txtCedCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCedCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedCliFocusLost(evt);
            }
        });
        txtCedCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedCliActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 58, 105, -1));

        txtConsecutivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConsecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsecutivoActionPerformed(evt);
            }
        });
        getContentPane().add(txtConsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 58, 90, -1));

        lblHabitacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHabitacion.setText("Habitación:");
        getContentPane().add(lblHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 232, -1, -1));

        lblCatHab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCatHab.setText("Categoría:");
        getContentPane().add(lblCatHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 232, -1, -1));

        lblFechaIni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaIni.setText("Ingreso:");
        getContentPane().add(lblFechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        lblFechaFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaFin.setText("Egreso:");
        getContentPane().add(lblFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        lblClaseHab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClaseHab.setText("Clase:");
        getContentPane().add(lblClaseHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 232, -1, -1));

        lblMonto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMonto.setText("Monto:");
        getContentPane().add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, 20));

        txtIdHab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIdHab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdHabFocusLost(evt);
            }
        });
        txtIdHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdHabActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 267, 81, -1));

        txtCat.setEditable(false);
        txtCat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatActionPerformed(evt);
            }
        });
        getContentPane().add(txtCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 267, 86, -1));

        txtClaseHab.setEditable(false);
        txtClaseHab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtClaseHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaseHabActionPerformed(evt);
            }
        });
        getContentPane().add(txtClaseHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 267, 83, -1));

        txtMonto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 74, -1));

        dtpInicio.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(dtpInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        dtpFin.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(dtpFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 38, 17));

        tblDetalle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Habitación", "Categoría", "Clase", "Ingreso", "Egreso", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalle.setToolTipText("");
        jScrollPane2.setViewportView(tblDetalle);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 673, 121));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock_dialog-error.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 30, 20));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock_new-text.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/document-save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtCedCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedCliActionPerformed

    private void txtConsecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsecutivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsecutivoActionPerformed

    private void txtIdHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdHabActionPerformed

    private void txtCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatActionPerformed

    private void txtClaseHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaseHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaseHabActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblDetalle.getModel();
        
        Object objNuevo[] = { txtIdHab.getText(), txtCat.getText(), txtClaseHab.getText(), 
            dtpInicio.getDate().toString(), dtpFin.getDate().toString(), txtMonto.getText()};
        
        modelo.addRow(objNuevo);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblDetalle.getModel();
        modelo.removeRow(tblDetalle.getSelectedRow());
    }//GEN-LAST:event_btnBorrarActionPerformed
    
    private void limpiar(){
        txtCedCli.setText("");
        txtCliente.setText("");
        txtDetalles.setText("");
        txtMonto.setText("");
        txtConsecutivo.setText("");
        cmbxEstado.setSelectedIndex(0);
    }
    
    private void limpiarDetalle(){
        txtCat.setText("");
        txtIdHab.setText("");
        txtClaseHab.setText("");
        LocalDate miFecha = LocalDate.now();
        ZoneId miZona = ZoneId.systemDefault();
        Date actual = Date.from(miFecha.atStartOfDay(miZona).toInstant());
        
        dtpInicio.setDate(actual);
        dtpFin.setDate(actual);
        
    }
    
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        limpiarDetalle();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtCedCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedCliFocusLost
        if ( !txtCedCli.getText().equals("") ){
            String nombreCliente = datos.BuscarCliente(txtCedCli.getText());
            if (!nombreCliente.equals("") ){
                txtCliente.setText(nombreCliente);
            }
        } else {
            txtCliente.setText("No encontrado");
            txtCedCli.requestFocus();
        }
    }//GEN-LAST:event_txtCedCliFocusLost

    private void txtIdHabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdHabFocusLost
        if ( !txtIdHab.getText().equals("")) {
            String nomClase = datos.BuscarClaseHab( Integer.parseInt(txtIdHab.getText()) );
            String nomCat = datos.BuscarCateHab( Integer.parseInt(txtCat.getText()) );
            
            txtClaseHab.setText(nomClase);
            txtCat.setText(nomCat);
        
        } else{
            txtClaseHab.setText("No encontrado");
            txtCat.setText("No encontrado");
        }
    }//GEN-LAST:event_txtIdHabFocusLost

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        objEncReserva miEnc = new objEncReserva();
        //miEnc.set...
        //datos.agregarEnc(miEnc);
        
        for (int i = 0; i < tblDetalle.getRowCount(); i++){
            String idHab = tblDetalle.getValueAt(i, 0).toString();
            String ingreso = tblDetalle.getValueAt(i, 3).toString();
            String egreso = tblDetalle.getValueAt(i, 4).toString();
            String costo = tblDetalle.getValueAt(i, 5).toString();
            
            objDetReserva miDet = new objDetReserva();
            //miDet.setIdHab(idHab);
            //datos.agregarDetalle(miDet);
            
        
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmReservas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbxEstado;
    private com.toedter.calendar.JDateChooser dtpFin;
    private com.toedter.calendar.JDateChooser dtpInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCatHab;
    private javax.swing.JLabel lblCedCli;
    private javax.swing.JLabel lblClaseHab;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaIni;
    private javax.swing.JLabel lblHabitacion;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNomCli;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtCat;
    private javax.swing.JTextField txtCedCli;
    private javax.swing.JTextField txtClaseHab;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtConsecutivo;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JTextField txtIdHab;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
