/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.estructuras;
import Datos.objDetalleLiq;
import Datos.objLiquidacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class frmLiquidaciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmLiquidaciones.class.getName());

    /**
     * Creates new form frmLiquidaciones
     */
    estructuras datos = new estructuras();
    
    public frmLiquidaciones() {
        //metdodos de carga dentro del frm
        initComponents();
        cargarEmpleadosActivos();
        cargarViaticosActivos();
        
        sldrHoraInicio.addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            int valor = sldrHoraInicio.getValue();
            lblHoraInicio.setText("Hora Inicio: " + valor + "h");
        });
        
        sldrHoraFin.addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            int valor = sldrHoraFin.getValue();
            lblHoraFin.setText("Hora Fin: " + valor + "h");
        });
        
        sldrHoraLlegada.addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            int valor = sldrHoraLlegada.getValue();
            lblHoraLlegada.setText("Hora Llegada: " + valor + "h");
        });
        
        sldrHoraSalida.addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            int valor = sldrHoraSalida.getValue();
            lblHoraSalida.setText("Hora Salida: " + valor + "h");
        });
    }
    
    private void cargarEmpleadosActivos(){
        cmbEmpleado.removeAllItems();
        
        ArrayList<String> idsEmpleados = datos.listaEmpleados();
        
        for ( String id : idsEmpleados ){
            cmbEmpleado.addItem(id);
        }
    }
    
    private void cargarViaticosActivos(){
        cmbViatico.removeAllItems();
        
        ArrayList<String> nombres = datos.listaViaticos();
        
        for ( String nombre : nombres ){
            cmbViatico.addItem(nombre);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblEmpleados = new javax.swing.JLabel();
        cmbEmpleado = new javax.swing.JComboBox<>();
        lblHoraLlegada = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JLabel();
        txtNombreEmp = new javax.swing.JTextField();
        lblNomEmpleado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJustificacion = new javax.swing.JTextArea();
        lblJustif = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        lblViaticos = new javax.swing.JLabel();
        cmbViatico = new javax.swing.JComboBox<>();
        dcFecha = new com.toedter.calendar.JDateChooser();
        lblFechaCons = new javax.swing.JLabel();
        lblHoraFin = new javax.swing.JLabel();
        lblHoraInicio = new javax.swing.JLabel();
        sldrHoraFin = new javax.swing.JSlider();
        sldrHoraInicio = new javax.swing.JSlider();
        lblMontoAplicado = new javax.swing.JLabel();
        txtMontoAplicado = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblObserva = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        sldrHoraLlegada = new javax.swing.JSlider();
        sldrHoraSalida = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Liquidaciones");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Registro de Liquidaciones");

        lblEmpleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmpleados.setText("IDs de Empleados:");

        cmbEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbEmpleadoFocusLost(evt);
            }
        });
        cmbEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpleadoActionPerformed(evt);
            }
        });

        lblHoraLlegada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraLlegada.setText("Hora Llegada:");

        lblHoraSalida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraSalida.setText("Hora Salida:");

        txtNombreEmp.setEditable(false);
        txtNombreEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpActionPerformed(evt);
            }
        });

        lblNomEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomEmpleado.setText("Empleado:");

        txtJustificacion.setColumns(20);
        txtJustificacion.setRows(5);
        jScrollPane1.setViewportView(txtJustificacion);

        lblJustif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJustif.setText("Justificación: ");

        cmbEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Liquidado" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setText("Estado:");

        tblDetalles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Empleado", "Hora de Llegada", "Hora de Salida", "Fecha de Consumo", "Viático", "Monto Aplicado", "Estado del Viático"
            }
        ));
        tblDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tblDetalles);

        lblViaticos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblViaticos.setText("Viáticos:");

        cmbViatico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbViatico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbViaticoFocusLost(evt);
            }
        });
        cmbViatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbViaticoActionPerformed(evt);
            }
        });

        dcFecha.setDateFormatString("dd/MM/yyyy");
        dcFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblFechaCons.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaCons.setText("Fecha de liquidación:");

        lblHoraFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraFin.setText("Hora Fin:");

        lblHoraInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraInicio.setText("Hora Inicio:");

        sldrHoraFin.setMaximum(24);
        sldrHoraFin.setValue(0);
        sldrHoraFin.setEnabled(false);

        sldrHoraInicio.setMaximum(24);
        sldrHoraInicio.setValue(0);
        sldrHoraInicio.setEnabled(false);

        lblMontoAplicado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMontoAplicado.setText("Monto Aplicado:");

        txtMontoAplicado.setEnabled(false);
        txtMontoAplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoAplicadoActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblObserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblObserva.setText("Observaciones:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtObservaciones.setRows(5);
        jScrollPane3.setViewportView(txtObservaciones);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAnular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAnular.setText("Anular");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        sldrHoraLlegada.setMaximum(24);
        sldrHoraLlegada.setValue(0);

        sldrHoraSalida.setMaximum(24);
        sldrHoraSalida.setValue(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblObserva)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnular)
                        .addGap(231, 231, 231))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmpleados)
                                        .addComponent(lblNomEmpleado))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombreEmp)
                                        .addComponent(cmbEmpleado, 0, 120, Short.MAX_VALUE))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHoraLlegada)
                                        .addComponent(lblJustif))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblEstado)
                                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnAgregar)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnEliminar))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(sldrHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(lblHoraSalida)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(sldrHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblViaticos)
                                    .addComponent(lblFechaCons))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbViatico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHoraInicio)
                                        .addGap(18, 18, 18)
                                        .addComponent(sldrHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHoraFin)
                                        .addGap(18, 18, 18)
                                        .addComponent(sldrHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMontoAplicado)
                                    .addComponent(txtMontoAplicado))))
                        .addGap(0, 70, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpleados)
                    .addComponent(cmbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraLlegada)
                    .addComponent(lblHoraSalida)
                    .addComponent(sldrHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldrHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNomEmpleado)
                                .addComponent(lblJustif))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViaticos)
                    .addComponent(cmbViatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoAplicado)
                    .addComponent(lblHoraInicio)
                    .addComponent(sldrHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaCons)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMontoAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHoraFin)
                        .addComponent(sldrHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObserva)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnAnular))
                        .addGap(96, 96, 96))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpleadoActionPerformed

    private void txtNombreEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void cmbViaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbViaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbViaticoActionPerformed

    private void txtMontoAplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoAplicadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoAplicadoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblDetalles.getModel();
        if (dcFecha.getDate() == null || txtMontoAplicado.getText().equals("") || sldrHoraLlegada.getValue() == 0 || sldrHoraSalida.getValue() == 0) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos para continuar...", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            if (sldrHoraLlegada.getValue() >= sldrHoraInicio.getValue() && sldrHoraLlegada.getValue() <= sldrHoraFin.getValue() &&
                    sldrHoraSalida.getValue() <= sldrHoraFin.getValue() && sldrHoraSalida.getValue() >= sldrHoraInicio.getValue() ){
                Object objNuevo[] = { txtNombreEmp.getText(), sldrHoraLlegada.getValue(), sldrHoraSalida.getValue(), 
                dcFecha.getDate().toString(), cmbViatico.getSelectedItem().toString(), txtMontoAplicado.getText(), cmbEstado.getSelectedItem().toString()};

                modelo.addRow(objNuevo);
                JOptionPane.showMessageDialog(this, "Se han agregado los detalles a la tabla", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            } else {
                JOptionPane.showMessageDialog(this, "La liquidació no se puede aplicar debido a que el empleado no cumple con la hora establecida del viátioo para ser aplicada", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbEmpleadoFocusLost
        Object itemEmp = cmbEmpleado.getSelectedItem();
        String empId = String.valueOf(itemEmp);
        String nombreEmp = datos.getNombreEmp(empId);
        if (datos.compruebaEstado(empId) != 0){
            JOptionPane.showMessageDialog(this, "Este Empleado se encuentra inactivo, por ende no puede realizarse una liquidación", "Información", JOptionPane.INFORMATION_MESSAGE);
            cmbEmpleado.setSelectedIndex(0);
        } else {
            txtNombreEmp.setText(nombreEmp);
        }
    }//GEN-LAST:event_cmbEmpleadoFocusLost

    private void cmbViaticoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbViaticoFocusLost
        Object itemViatico = cmbViatico.getSelectedItem();
        String nombreVia = String.valueOf(itemViatico);
        ArrayList<Integer> infoVia = datos.getInfoViatico(nombreVia);
        String monto = String.valueOf(infoVia.get(2));
        int horaInicio = infoVia.get(0); 
        int horaFin = infoVia.get(1);
        
        sldrHoraInicio.setValue(horaInicio);
        sldrHoraFin.setValue(horaFin);
        txtMontoAplicado.setText(monto);
    }//GEN-LAST:event_cmbViaticoFocusLost

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblDetalles.getModel();
        modelo.removeRow( tblDetalles.getSelectedRow() );

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (dcFecha.getDate() == null || txtMontoAplicado.getText().equals("") || sldrHoraLlegada.getValue() == 0 || sldrHoraSalida.getValue() == 0) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos para continuar...", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            int llegada = sldrHoraLlegada.getValue();
            int salida  = sldrHoraSalida.getValue();
            int inicio  = sldrHoraInicio.getValue(); 
            int fin     = sldrHoraFin.getValue();    
            if (!datos.dentroRango(llegada, salida, inicio, fin)){
                JOptionPane.showMessageDialog(this, "La liquidació no se puede aplicar debido a que el empleado no cumple con la hora establecida del viátioo para ser aplicada", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                objDetalleLiq detLiq = new objDetalleLiq(cmbEmpleado.getSelectedItem().toString(), txtNombreEmp.getText(), txtJustificacion.getText(), cmbViatico.getSelectedItem().toString(), txtObservaciones.getText());
                
                objLiquidacion liq = new objLiquidacion( cmbEstado.getSelectedItem().toString(), cmbEmpleado.getSelectedItem().toString(), sldrHoraLlegada.getValue(), sldrHoraSalida.getValue(), 
                Integer.parseInt(txtMontoAplicado.getText()), dcFecha.getDate().toString());
                if (txtJustificacion.getText().equals("") || txtObservaciones.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Debe completar todos los campos para continuar...", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {
                    datos.agregarLiq(liq);
                    datos.agregarDetL(detLiq);
                    JOptionPane.showMessageDialog(this, "Se ha agregado correctamente la liquidación!", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        if( datos.buscarBorrarLiqDet( cmbEmpleado.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(this, "Se ha anulado correctamente la liquidación!", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No existe liquidación...", "Aviso", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_btnAnularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmLiquidaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEmpleado;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbViatico;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEmpleados;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaCons;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblHoraLlegada;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblJustif;
    private javax.swing.JLabel lblMontoAplicado;
    private javax.swing.JLabel lblNomEmpleado;
    private javax.swing.JLabel lblObserva;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblViaticos;
    private javax.swing.JSlider sldrHoraFin;
    private javax.swing.JSlider sldrHoraInicio;
    private javax.swing.JSlider sldrHoraLlegada;
    private javax.swing.JSlider sldrHoraSalida;
    private javax.swing.JTable tblDetalles;
    private javax.swing.JTextArea txtJustificacion;
    private javax.swing.JTextField txtMontoAplicado;
    private javax.swing.JTextField txtNombreEmp;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
