/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.estructuras;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author sebas
 */
public class frmReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmReportes.class.getName());

    /**
     * Creates new form frmReportes
     */
    estructuras datos = new estructuras();
    public frmReportes() {
        initComponents();
        cargarEmpleadosActivos();
        initTabla();
    }
    
    
    
    private void initTabla() {
        model = new javax.swing.table.DefaultTableModel(
            new Object[]{"Fecha", "IdEmpleado", "Empleado", "Viatico", "Monto", "Justificación", "Obs"}, 0
        ){
            @Override public boolean isCellEditable(int r, int c){ return false; }
        };
        tblReporte.setModel(model);    
    }
    
    private void cargarEmpleadosActivos(){
        cmbEmpleadoId.removeAllItems();
        
        ArrayList<String> idsEmpleados = datos.listaEmpleados();
        
        for ( String id : idsEmpleados ){
            cmbEmpleadoId.addItem(id);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmpleado = new javax.swing.JLabel();
        cmbEmpleadoId = new javax.swing.JComboBox<>();
        btnBuscarEmpleado = new javax.swing.JButton();
        lblDesde = new javax.swing.JLabel();
        lblHasta = new javax.swing.JLabel();
        btnBuscarRango = new javax.swing.JButton();
        dcDesde = new com.toedter.calendar.JDateChooser();
        dcHasta = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotalTitulo = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");
        setResizable(false);

        lblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmpleado.setText("Buscar por empleado:");

        cmbEmpleadoId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnBuscarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarEmpleado.setText("Buscar");
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        lblDesde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDesde.setText("Desde:");

        lblHasta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHasta.setText("Hasta:");

        btnBuscarRango.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarRango.setText("Buscar");
        btnBuscarRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRangoActionPerformed(evt);
            }
        });

        dcDesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        dcHasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tblReporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "IdEmpleado", "Empleado", "IdLiquidación", "Viático", "Monto", "Obs"
            }
        ));
        jScrollPane1.setViewportView(tblReporte);

        lblTotalTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotalTitulo.setText("Total:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDesde)
                                .addGap(18, 18, 18)
                                .addComponent(dcDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHasta)
                                .addGap(18, 18, 18)
                                .addComponent(dcHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmpleado)
                                .addGap(18, 18, 18)
                                .addComponent(cmbEmpleadoId, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarEmpleado)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnBuscarRango))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalTitulo)
                                .addGap(56, 56, 56)
                                .addComponent(lblTotal))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpleado)
                    .addComponent(cmbEmpleadoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEmpleado))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDesde)
                        .addComponent(lblHasta))
                    .addComponent(dcDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRango))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalTitulo)
                    .addComponent(lblTotal))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private javax.swing.table.DefaultTableModel model;
    
    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        btnBuscarEmpleado.addActionListener(e -> {
            String id = (String) cmbEmpleadoId.getSelectedItem();
            if (id == null || id.isBlank()) {
                JOptionPane.showMessageDialog(this, "Seleccione un empleado.");
                return;
            }

            List<Object[]> filas = datos.reportePorEmpleado(id);
            model.setRowCount(0);
            for (Object[] r : filas) model.addRow(r);

            long total = 0L;
            for (Object[] r : filas) {
                Object valor = r[4]; // columna del monto
                if (valor == null) continue;
                try {
                    total += Long.parseLong(valor.toString());
                } catch (NumberFormatException ex) {
                    System.out.println("Valor no numérico en monto: " + valor);
                }
            }
            lblTotal.setText(String.valueOf(total));
        });
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnBuscarRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRangoActionPerformed
        var desde = toLocalDate(dcDesde);
        var hasta = toLocalDate(dcHasta);

        if (desde == null || hasta == null || hasta.isBefore(desde)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Rango de fechas inválido.");
            return;
        }

        var filas = datos.reportePorRango_Detallado(desde, hasta);

        model.setRowCount(0);
        for (Object[] r : filas) model.addRow(r);

        long total = 0L;
        for (Object[] r : filas) {
            Object v = r[4]; // Monto
            if (v != null) {
                try { total += Long.parseLong(v.toString()); } catch (NumberFormatException ignore) {}
            }
        }
        lblTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnBuscarRangoActionPerformed

    
    private java.time.LocalDate toLocalDate(com.toedter.calendar.JDateChooser dc){
        if (dc.getDate() == null) return null;
        return dc.getDate().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnBuscarRango;
    private javax.swing.JComboBox<String> cmbEmpleadoId;
    private com.toedter.calendar.JDateChooser dcDesde;
    private com.toedter.calendar.JDateChooser dcHasta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalTitulo;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
