/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.estructuras;
import Datos.objUsuario;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class frmUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmUsuarios.class.getName());
    
    estructuras datos = new estructuras();

    /**
     * Creates new form frmUsuarios
     */
    public frmUsuarios() {
        initComponents();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCedula = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblEmpresaId = new javax.swing.JLabel();
        lblNombreUsr = new javax.swing.JLabel();
        lblNombreCom = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        cmbxEstado = new javax.swing.JComboBox<>();
        cmbxRol = new javax.swing.JComboBox<>();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombreComp = new javax.swing.JTextField();
        txtNombreUsr = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsuarios = new javax.swing.JList<>();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Usuarios");
        setResizable(false);

        lblCedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCedula.setText("Cédula:");

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setText("Estado:");

        lblRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRol.setText("Rol:");

        lblEmpresaId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmpresaId.setText("Identificación:");

        lblNombreUsr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreUsr.setText("Nombre Usuario:");

        lblNombreCom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreCom.setText("Nombre Completo:");

        lblClave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClave.setText("Contraseña:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Registro de Usuarios");

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        cmbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        cmbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario", "Empleado" }));

        txtIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });

        txtNombreComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCompActionPerformed(evt);
            }
        });

        txtNombreUsr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombreUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsrActionPerformed(evt);
            }
        });

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lstUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(lstUsuarios);

        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(308, 308, 308))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(41, 41, 41)
                        .addComponent(btnBorrar)
                        .addGap(54, 54, 54)
                        .addComponent(btnBuscar)
                        .addGap(45, 45, 45)
                        .addComponent(btnLimpiar)
                        .addGap(95, 95, 95)
                        .addComponent(btnConsultar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCom)
                            .addComponent(lblRol, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmpresaId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblClave, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombreUsr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCedula, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedula)
                            .addComponent(cmbxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbxRol, javax.swing.GroupLayout.Alignment.TRAILING, 0, 180, Short.MAX_VALUE)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreComp)
                            .addComponent(txtNombreUsr)
                            .addComponent(txtClave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedula)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(cmbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRol)
                            .addComponent(cmbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpresaId)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCom)
                            .addComponent(txtNombreComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreUsr)
                            .addComponent(txtNombreUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClave)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBorrar)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnConsultar))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void txtNombreCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompActionPerformed

    private void txtNombreUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsrActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.limpiar();
        JOptionPane.showMessageDialog(this, "Se limpiaron todos los campos!!!", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        DefaultListModel modeloUsr = datos.listarUsuarios();
        lstUsuarios.setModel(modeloUsr);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void limpiar(){
        txtCedula.setText("");
        txtClave.setText("");
        txtIdentificacion.setText("");
        txtNombreComp.setText("");
        txtNombreUsr.setText("");
        cmbxRol.setSelectedIndex(0);
        cmbxEstado.setSelectedIndex(0);
    }
    
    
    private void guardar () {
        int cedula = Integer.parseInt(txtCedula.getText());
        String nombreUsr = txtNombreUsr.getText();
        String nombreCompl = txtNombreComp.getText();
        int estado = cmbxEstado.getSelectedIndex();
        String clave = new String( txtClave.getPassword() );
        String usrId = txtIdentificacion.getText();
        int rol = cmbxRol.getSelectedIndex();
        int idx = datos.getIndexUsr( cedula );
        
        
        objUsuario usr = new objUsuario(cedula, estado, usrId, nombreCompl, nombreUsr, clave, rol);
        
        if (idx != -1) {
            datos.modUsr(idx, usr);
            JOptionPane.showMessageDialog(this, "Se ha modificado el usuario correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        
        } else {
            datos.agregarUsr(usr);
            JOptionPane.showMessageDialog(this, "Se ha guardado el usuario correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        }
    
    }
    
    
    private int comprobar () {
        String regex = "^\\d+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtCedula.getText());
        if ( matcher.matches()){
            String clave = new String(txtClave.getPassword());
            if ( clave.equals("") || txtNombreUsr.getText().equals("") || txtNombreComp.getText().equals("")){
                return 2;
            }
        } else {
            return 1;
        }
        return 0;
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        switch ( comprobar() ) {
            case 0: guardar();
                break;
            case 1: JOptionPane.showMessageDialog(this, "Solo se permiten números para el ID...", "Aviso", JOptionPane.WARNING_MESSAGE);
                break;
            case 2: JOptionPane.showMessageDialog(this, "Debe completar todos los espacios disponibles!", "Aviso", JOptionPane.WARNING_MESSAGE);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String regex = "^\\d+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtCedula.getText());

        if (matcher.matches()){
            if (datos.buscarBorrarUsr(Integer.parseInt(txtCedula.getText() ))){
                JOptionPane.showMessageDialog(this, "Usuario borrado!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtCedula.setText("");
            } else{
                JOptionPane.showMessageDialog(this, "Usuario no encontrado...", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo indentificación solo admite numeros", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtCedula.setText("");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String regex = "^\\d+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtCedula.getText());

        if (matcher.matches()){
            int id = Integer.parseInt(txtCedula.getText());
            objUsuario usr = datos.getUsr( id );

            if (usr != null){
                JOptionPane.showMessageDialog(this, "Usuario encontrado!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtClave.setText("");
                txtIdentificacion.setText(usr.getIdentificacion());
                cmbxEstado.setSelectedIndex(usr.getEstado());
                txtNombreComp.setText(usr.getNombreCompleto());
                txtNombreUsr.setText(usr.getNombreUsr());
                cmbxRol.setSelectedIndex(usr.getRol());
            } else {
                JOptionPane.showMessageDialog(this, "El ID digitado no existe", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtCedula.setText("");
            }
            

        } else{
            JOptionPane.showMessageDialog(this, "El campo indentificacion solo admite numeros", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbxEstado;
    private javax.swing.JComboBox<String> cmbxRol;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblEmpresaId;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombreCom;
    private javax.swing.JLabel lblNombreUsr;
    private javax.swing.JLabel lblRol;
    private javax.swing.JList<String> lstUsuarios;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombreComp;
    private javax.swing.JTextField txtNombreUsr;
    // End of variables declaration//GEN-END:variables
}
