/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.estructuras;
import Datos.objViatico;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class frmViaticos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmViaticos.class.getName());
    
    /**
     * Creates new form frmViaticos
     */
    estructuras datos = new estructuras();
    
    public frmViaticos() {
        initComponents();
        configSincro();
        
        sldrHoraSalida.addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            int valor = sldrHoraSalida.getValue();
            lblHoraFin.setText("Hora Fin: " + valor + "h");
        });
        
        sldrHoraLlegada.addChangeListener((javax.swing.event.ChangeEvent evt) -> {
            int valor = sldrHoraLlegada.getValue();
            lblHoraInicio.setText("Hora Inicio: " + valor + "h");
        });
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblViaticoID = new javax.swing.JLabel();
        lblNombreVia = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        sldrMonto = new javax.swing.JSlider();
        cmbxEstado = new javax.swing.JComboBox<>();
        txtNombreVia = new javax.swing.JTextField();
        txtViaticoID = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstViaticos = new javax.swing.JList<>();
        btnConsultar = new javax.swing.JButton();
        lblMontoSlider = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblHoraInicio = new javax.swing.JLabel();
        lblHoraFin = new javax.swing.JLabel();
        sldrHoraSalida = new javax.swing.JSlider();
        sldrHoraLlegada = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Viáticos");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Viáticos");

        lblViaticoID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblViaticoID.setText("ID Viático:");

        lblNombreVia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreVia.setText("Nombre del Viático:");

        lblMonto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMonto.setText("Monto:");

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setText("Estado del viático:");

        sldrMonto.setMaximum(144225);
        sldrMonto.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                sldrMontoVetoableChange(evt);
            }
        });

        cmbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstViaticos);

        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblMontoSlider.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMontoSlider.setText("₡");

        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        lblHoraInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraInicio.setText("Hora Inicio:");

        lblHoraFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraFin.setText("Hora Fin:");

        sldrHoraSalida.setMaximum(24);
        sldrHoraSalida.setValue(0);

        sldrHoraLlegada.setMaximum(24);
        sldrHoraLlegada.setToolTipText("");
        sldrHoraLlegada.setValue(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreVia)
                            .addComponent(lblEstado)
                            .addComponent(lblMonto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblViaticoID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbxEstado, 0, 168, Short.MAX_VALUE)
                            .addComponent(sldrMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtNombreVia)
                            .addComponent(txtViaticoID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMontoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(41, 41, 41)
                                .addComponent(btnBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHoraInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sldrHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblHoraFin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sldrHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(64, 64, 64)
                                .addComponent(btnLimpiar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblViaticoID)
                            .addComponent(txtViaticoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreVia)
                            .addComponent(txtNombreVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMonto)
                            .addComponent(sldrMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMontoSlider)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(cmbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sldrHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sldrHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraInicio)
                            .addComponent(lblHoraFin))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnBorrar)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpiar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnConsultar)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean actualizando = false;
    
    private void configSincro(){
        sldrMonto.setMinimum(0);
        sldrMonto.setMaximum(144225);
        
        sldrMonto.addChangeListener(evt -> {
            if (actualizando) return;
            actualizando = true;
            try {
                int v = sldrMonto.getValue();
                txtMonto.setText(String.valueOf(v));  // o formateado
            } finally {
                actualizando = false;
            }
        });
        
        txtMonto.addActionListener(e -> actualizarSliderDesdeTexto());
        
        txtMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                actualizarSliderDesdeTexto();
            }
        });
    }
    
    private void actualizarSliderDesdeTexto(){
        if (actualizando) return;
        actualizando = true;
        try{
            String t = txtMonto.getText().trim();

            // Permitir vacío momentáneo
            if (t.isEmpty()) {
                actualizando = false;
                return;
            }

            t = t.replace("₡", "").replace(",", "").replace(" ", "");

            int valor = Integer.parseInt(t);
            int min = sldrMonto.getMinimum();
            int max = sldrMonto.getMaximum();
            if (valor < min) valor = min;
            if (valor > max) valor = max;

            if (sldrMonto.getValue() != valor) {
                sldrMonto.setValue(valor);
            }

            
            txtMonto.setText(String.valueOf(valor));
        
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            actualizando = false;
        }
    }
    
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.limpiar();
        JOptionPane.showMessageDialog(this, "Se han limpiado los campos!", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        DefaultListModel modeloVia = datos.listarViaticos();
        lstViaticos.setModel(modeloVia);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void sldrMontoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_sldrMontoVetoableChange

    }//GEN-LAST:event_sldrMontoVetoableChange

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private int comprobar(){
        String regex = "^\\d+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtViaticoID.getText());
        if ( matcher.matches()){
            if (txtMonto.getText().isEmpty() || txtNombreVia.getText().equals("")){
                return 2;
            }
        
        } else {
            return 1;
        }
        return 0;
    }
    
    private void limpiar(){
        txtViaticoID.setText("");
        txtMonto.setText("");
        txtNombreVia.setText("");
        sldrHoraLlegada.setValue(0);
        sldrHoraSalida.setValue(0);
        sldrMonto.setValue(0);
        cmbxEstado.setSelectedIndex(0);
    }
    
    private void guardar(){
        int id = Integer.parseInt(txtViaticoID.getText());
        String nombreVia = txtNombreVia.getText();
        int valorVia = sldrMonto.getValue();
        int estado = cmbxEstado.getSelectedIndex();
        int horaLlegada = sldrHoraLlegada.getValue();
        int horaSalida = sldrHoraSalida.getValue();
        int idx = datos.getViaIdx(id);
        
        objViatico via = new objViatico(id, nombreVia, valorVia, estado, horaLlegada, horaSalida);
        
        if (idx != -1) {
            datos.modVia(idx, via);
            JOptionPane.showMessageDialog(this, "Se ha modificado el viático correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        
        } else {
            datos.agregarVia(via);
            JOptionPane.showMessageDialog(this, "Se ha guardado el viático correctamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
        }
        
        
    
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        switch ( comprobar() ) {
            case 0: guardar();
                break;
            case 1: JOptionPane.showMessageDialog(this, "Solo se permiten números para el ID...", "Aviso", JOptionPane.WARNING_MESSAGE);
                break;
            case 2: JOptionPane.showMessageDialog(this, "Debe completar todos los espacios disponibles!", "Aviso", JOptionPane.WARNING_MESSAGE);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String regex = "^\\d+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtViaticoID.getText());

        if (matcher.matches()){
            if (datos.buscarBorrarVia(Integer.parseInt(txtViaticoID.getText() ))){
                JOptionPane.showMessageDialog(this, "Viático borrado!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtViaticoID.setText("");
            } else{
                JOptionPane.showMessageDialog(this, "Viático no encontrado...", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo indentificación solo admite numeros", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtViaticoID.setText("");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String regex = "^\\d+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(txtViaticoID.getText());

        if (matcher.matches()){
            int id = Integer.parseInt(txtViaticoID.getText());
            objViatico via = datos.getVia( id );

            if (via != null){
                JOptionPane.showMessageDialog(this, "Viático encontrado!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                txtNombreVia.setText(via.getNomViatico());
                sldrMonto.setValue(via.getMonto());
                cmbxEstado.setSelectedIndex(via.getEstado());
                sldrHoraLlegada.setValue(via.getHoraLlegada());
                sldrHoraSalida.setValue(via.getHoraSalida());
            } else {
                JOptionPane.showMessageDialog(this, "El id digitado no existe", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtViaticoID.setText("");
            }
            

        } else{
            JOptionPane.showMessageDialog(this, "El campo indentificacion solo admite numeros", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmViaticos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblMontoSlider;
    private javax.swing.JLabel lblNombreVia;
    private javax.swing.JLabel lblViaticoID;
    private javax.swing.JList<String> lstViaticos;
    private javax.swing.JSlider sldrHoraLlegada;
    private javax.swing.JSlider sldrHoraSalida;
    private javax.swing.JSlider sldrMonto;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombreVia;
    private javax.swing.JTextField txtViaticoID;
    // End of variables declaration//GEN-END:variables
}
